- template:
    src: i18n.j2
    dest: /etc/sysconfig/i18n
    owner: root
    group: root
    mode: 0664
  when: ansible_os_family == 'RedHat'

- template:
    src: clock.j2
    dest: /etc/sysconfig/clock
    owner: root
    group: root
    mode: 0664
  when: ansible_os_family == 'RedHat'

- service: name=crond enabled=yes state=restarted
  when: ansible_os_family == 'RedHat'
- service: name=cron enabled=yes state=restarted
  when: ansible_os_family == 'Debian'
